function [dq_skew] = dq_skew(dq)
%DQ_SKEW Calculate the skew matrix of the dual quaternion
%   dq_skew = [ar^x, zeros(3);...
%              ad^x, ar^x];

arx = [0, -dq(4), dq(3);...
       dq(4), 0, -dq(2);...
       -dq(3), dq(2), 0];
adx = [0, -dq(8), dq(7);...
       dq(8), 0, -dq(6);...
       -dq(7), dq(6), 0];

   dq_skew = [arx, zeros(3);...
              adx, arx];
end

