function [output] = dual_quat_mult(dq,dp)
%DUAL_QUAT_MULT right dual quaternion multiplication of dq and dp
%   output = dq*dp
Mr = [dq(1), -dq(2), -dq(3), -dq(4);...
      dq(2), dq(1), -dq(4), dq(3);...
      dq(3), dq(4), dq(1), -dq(2);...
      dq(4), -dq(3), dq(2), dq(1)];
Md = [dq(5), -dq(6), -dq(7), -dq(8);...
      dq(6), dq(5), -dq(8), dq(7);...
      dq(7), dq(8), dq(5), -dq(6);...
      dq(8), -dq(7), dq(6), dq(5)];
  
M = [Mr, zeros(4);...
     Md, Mr];

output = M*dp;
end

