function dwz_cross = get_Z(z)
%GET_Z Summary of this function goes here
%   Detailed explanation goes here
wz1_cross = [0, 0, 0, 0;...
            z(2), z(1), z(4), -z(3);...
            z(3), -z(4), z(1), z(2);...
            z(4), z(3), -z(2), z(1)];
wz2_cross = [0, 0, 0, 0;...
            z(6), z(5), z(8), -z(7);...
            z(7), -z(8), z(5), z(6);...
            z(8), z(7), -z(6), z(5)];
        
dwz_cross = [wz1_cross, zeros(4);...
               wz2_cross, wz1_cross];
end

