function M_dq = get_left_dquat_mat(dq)
%GET_LEFT_DQUAT_MAT This function returns the left dual quaternion
%multiplication Matrix
%   When dual_o = M(dual_p)*dual_q then this function returns M(dual_p)


Mr = [dq(1), -dq(2), -dq(3), -dq(4);...
    dq(2), dq(1), -dq(4), dq(3);...
    dq(3), dq(4), dq(1), -dq(2);...
    dq(4), -dq(3), dq(2), dq(1)];
Md = [dq(5), -dq(6), -dq(7), -dq(8);...
    dq(6), dq(5), -dq(8), dq(7);...
    dq(7), dq(8), dq(5), -dq(6);...
    dq(8), -dq(7), dq(6), dq(5)];

M_dq = [Mr, zeros(4);...
    Md, Mr];


end

