function Z_dq = get_cross_dquat_mat(dq)
%GET_CROSS_DQUAT_MAT Summary of this function goes here
%   Detailed explanation goes here
dq1_cross = [0, 0, 0, 0;...
            dq(2), dq(1), -dq(4), dq(3);...
            dq(3), dq(4), dq(1), -dq(2);...
            dq(4), -dq(3), dq(2), dq(1)];
dq2_cross = [0, 0, 0, 0;...
            dq(6), dq(5), -dq(8), dq(7);...
            dq(7), dq(8), dq(5), -dq(6);...
            dq(8), -dq(7), dq(6), dq(5)];
        
Z_dq = [dq1_cross, zeros(4);...
               dq2_cross, dq1_cross];
end

